// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCtTMzEaa0oJC7PTl7jjaW0gBiXlSM5WY',
    appId: '1:795717818913:web:6c08d52d81d66db4326160',
    messagingSenderId: '795717818913',
    projectId: 'h24voyage',
    authDomain: 'h24voyage.firebaseapp.com',
    storageBucket: 'h24voyage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8PqwG5UebbBOpgIpvafyhjnjhARfbgug',
    appId: '1:795717818913:android:b70b51324e4440f7326160',
    messagingSenderId: '795717818913',
    projectId: 'h24voyage',
    storageBucket: 'h24voyage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsGi2zJWEE2iTp-vK4-GGgbkxmhAeQ5SM',
    appId: '1:795717818913:ios:615f9a19068df61e326160',
    messagingSenderId: '795717818913',
    projectId: 'h24voyage',
    storageBucket: 'h24voyage.firebasestorage.app',
    iosBundleId: 'com.maantheme.flightBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsGi2zJWEE2iTp-vK4-GGgbkxmhAeQ5SM',
    appId: '1:795717818913:ios:615f9a19068df61e326160',
    messagingSenderId: '795717818913',
    projectId: 'h24voyage',
    storageBucket: 'h24voyage.firebasestorage.app',
    iosBundleId: 'com.maantheme.flightBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCtTMzEaa0oJC7PTl7jjaW0gBiXlSM5WY',
    appId: '1:795717818913:web:189a8a0f24611ef3326160',
    messagingSenderId: '795717818913',
    projectId: 'h24voyage',
    authDomain: 'h24voyage.firebaseapp.com',
    storageBucket: 'h24voyage.firebasestorage.app',
  );

}